class Create_mail:
    expected_name = "alex2019hillel@ukr.net"

    create_button = "//div[@id='content']/aside/button"
    fild_input = "//input[@name='toFieldInput']"
    fild_subject = "//input[@name='subject']"
    #fild_description = "// div[ @class ='fmedit']//div[2]"
    #fild_description = "//div[@class='screen__content']/section[@class='sendmsg__area']//div[@class='editor__area sendmsg']"
    fild_description = "//body[@id='tinymce']/div/span"
    #fild_description = "//button[@type='button'])[22]"
    fild_descriptions = "//span[@class='customFontStyle']"
    #submit_button = "//div[@id='screens']/div/div/div/button"
    submit_button = "//div[@class='controls']/button"
    fild_descr = "//div[@class='screens']//div[@class='sendmsg__area']//div[@class='editor']"
    ###submit_button = "//div[@class='screen__head']//div[@class='controls']/button"
    new_create_button = "//a[@id='0']/span[4]"
    #action = "//[@class='action']"
    #action_button = "//div[@class='controls']/button"
    link_button = "//div[@id='screens']/div/div[3]/div/div[2]/a"

    content_fild = "//td[@class='msglist__row-subject']/a"
    #new_create_button = "//div[@id ='squareD']/div/canvas[2]"
    in_mail_box = "//a[@id='0']//span[@class='sidebar__list-link-name']"
    row_check = "//td[@class='msglist__row-check']//input"
    delete_button = "//div[@class='msglist__controls']/a[2]"
    #$x("//xpath")